version: ~> 1.0
dist: focal
language: python
python:
  - "3.11"
install:
  # pipをアップグレードする理由: pipのバージョンが古いと、pillowなど環境ごとにwheelを提供しているライブラリのインストールに失敗する可能性があるため
  - pip install pip --upgrade
  - pip install 'poetry<1.5'
  # travis_retryを使う理由: インストール時にtimeoutで失敗しないようにするため
  - travis_retry poetry install --without formatter

script:
   - make lint
branches:
  only:
  - main

cache: pip
